/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import mypackage.MyClassname;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println(MyClassname.A.newBuilder().setA("hello").build().getA());
        return true;
    }
}
