/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

public class Library {
    public boolean someLibraryMethod() {
        mypackage.Myclassname.A.newBuilder();
        return true;
    }
}
